language: php
sudo: false
php:
 - '5.5'
 - '5.6'
 - '7.0'
 - nightly
before_script:
 - pyrus install pear/PHP_CodeSniffer
 - phpenv rehash
script:
 - make sniff || echo "Completed - Returned $?"
 - make test
