language: php
sudo: false
php:
 - '5.5'
 - '5.6'
 - '7.0'
 - nightly
before_script:
 - phpenv rehash
install:
 - composer self-update
 - composer require squizlabs/php_codesniffer
 - composer install
script:
 - make sniff || echo "Completed - Returned $?"
 - make test
