language: php
php:
 - 5.5
 - 5.6
before_script:
 - pyrus install http://phptal.org/latest.tar.gz
 - pear install pear/PHP_CodeSniffer
 - phpenv rehash
script:
 - phpcs --standard=test/phpcs-ganglia-web.xml -p *.php api graph.d lib nagios test || echo "Completed - Returned $?"
 - phpunit test
